#!/bin/bash

#sh -x task.sh ${USER_SIMILARITY_MERGE_INPUT_PATH}/0000[0-4]/ ${USER_SIMILARITY_MERGE_OUTPUT_PATH}/PART-0
sh -x task.sh ${USER_SIMILARITY_MERGE_INPUT_PATH}/0000[5-9]/ ${USER_SIMILARITY_MERGE_OUTPUT_PATH}/PART-1
